[package]
name = "simplehttpserver"
version = "0.1.0"
authors = ["Michael Zhang <failed.down@gmail.com>"]

[dependencies]
rocket = "0.3.3"
rocket_codegen = "0.3.3"
serde = "1.0.15"
serde_derive = "1.0.15"

[dependencies.rocket_contrib]
version = "0.3.3"
features = ["handlebars_templates"]

